# feature set for each data set
merged-files: 
  feature_list: ['model', 'extension', 'location', 'working_hours', 'const_year', 'price'] # complete feature list
  basic_subset: ['model', 'working_hours', 'const_year'] # this is the basic subset
  extended_features: ['extension', 'location'] # features that should be within the combinatorial
  label: ['price'] # label
