pca_num: 0 # max number of principal components (features)

random_state: 1 # set random state

bin_outlier_detect: True # set the additional outlier detection within bins (True or False)

datasets: ['merged-files', 'Caterpillar-308', 'Caterpillar-320', 'Caterpillar-323', 'Caterpillar-329', 'Caterpillar-330', 'Caterpillar-336', 'Caterpillar-950', 'Caterpillar-966', 'Caterpillar-D6', 'Caterpillar-M318',]

algorithms: ["manual", "nn", "autosklearn", "autogluon", "flaml", "autokeras"]

documentation: True # set the documentation (True or False)

measurement_num: 5 # number of repetitive measurements

# set preprocessing for automl methods
automl_preprocessing: False

# evaluate data set variance
evaluate_dataset_variance: True

# set method evaluation value weights
mev_weights:
    correctness: 50
    expertise: 40
    complexity: 10 
    responsiveness: 0 
    reproducability: 0

# set knowledge levels
knowledge_levels:
    manual_methods: 5
    automl_methods: 2